import path from 'node:path';import{normalizeGutenbergBlocks}from'./gutenberg-utils.mjs';import{existsSync}from'node:fs';import{readFile,writeFile}from'node:fs/promises';import{argvValue}from'./workflow-utils.mjs';import{atomicWrite,capbox,els,findSection,fragNodes,hasClass,isIn,loadDecorationConfig,parseFragment,replace,sectionNodes,serialize,setAttr,sourceFile,text,assignHeadingIds,attr,before,after,sha256,validateMarkerPlacement,walk,esc}from'./decoration-utils.mjs';
const DEFAULT_DECORATION={version:1,enabled:true,outline:{enabled:true,title:'【この記事でわかること】'},section_navigation:{enabled:true,minimum_h3:3,default_title:'この章でわかること',overrides:[]},list_boxes:[],markers:[]};
const POSITIVE_PATTERNS=['費用は無料','追加費用はかかりません','保険があるので安心','キャンセル料は無料','手続きの負担を減らせます','無料','安心','おすすめ','メリット','選びやす','候補','満足','できる','可能','スムーズ','重要です','確認しましょう'];
const NEGATIVE_PATTERNS=['追加費用が発生','費用が発生','料金が発生','発生します','発生する','契約を急か','急かされ','売却を迫','保険が適用されない','キャンセル料が発生','税金の負担が残る','対象外','できません','できず','不可','高くなる','違約金','トラブル','リスク','デメリット','事故','不動','紛失','向かない','誤解'];
async function readOrCreateConfig(dir){if(existsSync(path.join(dir,'decoration.json')))return loadDecorationConfig(dir); return structuredClone(DEFAULT_DECORATION)}
function unmark(root){for(const n of els(root,'span').filter(n=>hasClass(n,'swl-marker')&&hasClass(n,'mark_yellow')))replace(root,n,n.childNodes||[]);for(const n of els(root,'mark').filter(n=>hasClass(n,'has-swl-deep-01-color')))replace(root,n,n.childNodes||[])}
function wrapList(root,ul,title){setAttr(ul,'class',[attr(ul,'class'),'wp-block-list'].filter(Boolean).join(' '));replace(root,ul,fragNodes(`<!-- wp:loos/cap-block {"className":"is-style-onborder_ttl"} --><div class="swell-block-capbox cap_box is-style-onborder_ttl"><div class="cap_box_ttl"><span>${title}</span></div><div class="cap_box_content"><!-- wp:list -->${serialize({childNodes:[ul]}).trim()}<!-- /wp:list --></div></div><!-- /wp:loos/cap-block -->`))}
function markerParagraphs(root,heading){return directSectionNodes(root,heading).filter(n=>n.tagName==='p'&&!isIn(root,n,x=>['ul','ol','table','thead','tbody','tr','td','th'].includes(x.tagName)||hasClass(x,'swell-block-capbox')))}
function markerTag(m){return m.tone==='negative'?`<mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-swl-deep-01-color">${esc(m.text)}</mark>`:`<span class="swl-marker mark_yellow">${esc(m.text)}</span>`}
function paragraphSignature(p){return sha256(text(p).replace(/\s+/g,' ').trim())}
function applyMarker(root,heading,m){const paragraphs=markerParagraphs(root,heading); const scoped=Number.isInteger(m.paragraph_index)?[paragraphs[m.paragraph_index]].filter(Boolean):paragraphs; if(Number.isInteger(m.paragraph_index)&&m.paragraph_text_sha256&&scoped[0]&&paragraphSignature(scoped[0])!==m.paragraph_text_sha256)throw new Error(`マーカー対象段落が一致しません: ${m.text}`); let found=[]; let crossesInline=false; for(const p of scoped){walk(p,n=>{if(n.nodeName!=='#text')return; if(isIn(root,n,x=>['a','code','kbd','samp','pre'].includes(x.tagName)))return; if((n.value||'').includes(m.text))found.push(n);}); if(!found.length&&text(p).includes(m.text))crossesInline=true;} if(found.length!==1){if(crossesInline)throw new Error(`マーカー文字列がインライン要素をまたぐため適用できません: ${m.text}`); throw new Error(`マーカー文字列を一意に特定できません: ${m.text}`);} const tn=found[0]; const [beforeText,...rest]=(tn.value||'').split(m.text); const afterText=rest.join(m.text); replace(root,tn,fragNodes(`${esc(beforeText)}${markerTag(m)}${esc(afterText)}`));}
function directSectionNodes(root,h){const nodes=sectionNodes(root,h); if(h.tagName!=='h2')return nodes; const i=nodes.findIndex(n=>n.tagName==='h3'); return i>=0?nodes.slice(0,i):nodes;}
function phraseFromText(s){const raw=s.replace(/\s+/g,' ').trim(); if(!raw)return''; const sentences=raw.split(/(?<=[。！？])/).map(x=>x.trim()).filter(Boolean); const choices=[...sentences,raw]; for(const c of choices){const phrase=c.length>60?c.slice(0,60).replace(/[、。！？]$/,''):c; if(phrase.length>=8)return phrase} return'';}
function markerTextFromParagraph(root,p){let picked=''; walk(p,n=>{if(picked||n.nodeName!=='#text')return; if(isIn(root,n,x=>['a','strong','code','em','span','mark','kbd','samp','pre'].includes(x.tagName)))return; picked=phraseFromText(n.value||'');}); const html=serialize({childNodes:[p]}); return picked&&html.includes(picked)?picked:'';}
function inferTone(s){if(POSITIVE_PATTERNS.some(w=>s.includes(w)))return 'positive'; if(NEGATIVE_PATTERNS.some(w=>s.includes(w)))return 'negative'; return 'positive'}
function autoGenerateMarkers(root,cfg){cfg.markers=Array.isArray(cfg.markers)?cfg.markers:[]; const has=(h)=>cfg.markers.some(m=>Number(m.section?.level||2)===Number(h.tagName.slice(1))&&((m.section?.id&&m.section.id===attr(h,'id'))||(!m.section?.id&&m.section?.heading===text(h).trim()))); for(const h of [...els(root,'h2'),...els(root,'h3')]){if(has(h))continue; const p=directSectionNodes(root,h).find(n=>n.tagName==='p'&&!isIn(root,n,x=>hasClass(x,'swell-block-capbox')||['li','ul','ol','table','thead','tbody','tr','td','th'].includes(x.tagName))&&text(n).trim()&&els(n,'a').length===0); if(!p)continue; const mt=markerTextFromParagraph(root,p); if(!mt)continue; cfg.markers.push({section:{level:Number(h.tagName.slice(1)),id:attr(h,'id'),heading:text(h).trim()},paragraph_index:markerParagraphs(root,h).indexOf(p),paragraph_text_sha256:paragraphSignature(p),tone:inferTone(mt),text:mt});} return cfg;}
async function saveConfig(dir,cfg){await writeFile(path.join(dir,'decoration.json'),JSON.stringify(cfg,null,2)+'\n')}
export async function decorate(slug){const dir=path.join('articles',slug); const cfg=await readOrCreateConfig(dir); const src=await sourceFile(dir); const html=await readFile(src,'utf8'); const root=parseFragment(html); assignHeadingIds(root); unmark(root); autoGenerateMarkers(root,cfg); await saveConfig(dir,cfg); const h2s=els(root,'h2'); if(!h2s.length)throw new Error('H2がありません'); before(root,h2s[0],capbox(cfg.outline?.title||'【この記事でわかること】',h2s.map(h=>({id:attr(h,'id'),title:text(h).trim()})))); for(const h2 of h2s){const nodes=sectionNodes(root,h2), h3s=nodes.filter(n=>n.tagName==='h3'); const ov=(cfg.section_navigation?.overrides||[]).find(o=>o.section&&text(h2).trim()===o.section.heading); const min=ov?.minimum_h3||cfg.section_navigation?.minimum_h3||3; const enabled=ov?.enabled!==false&&cfg.section_navigation?.enabled!==false; if(enabled&&h3s.length>=min){const p=nodes.find(n=>n.tagName==='p'); if(!p)throw new Error(`H2直下の導入文がありません: ${text(h2).trim()}`); after(root,p,capbox(ov?.title||cfg.section_navigation?.default_title||'この章でわかること',h3s.map(h=>({id:attr(h,'id'),title:text(h).trim()}))));}}
 for(const lb of cfg.list_boxes||[]){if(!lb.title||['ここにタイトル','タイトルA','タイトルB','リスト','ポイント','項目'].includes(lb.title))throw new Error('capboxタイトルが不正です'); const h=findSection(root,lb.section); const lists=sectionNodes(root,h).filter(n=>n.tagName==='ul'&&!isIn(root,n,x=>['ul','table','nav','pre','code'].includes(x.tagName)||hasClass(x,'swell-block-capbox')||/cta/i.test(attr(x,'class')))); const ul=lists[(lb.list_index||1)-1]; if(!ul)throw new Error(`対象ulがありません: ${lb.title}`); wrapList(root,ul,lb.title)}
 for(const m of cfg.markers||[]){if(!['positive','negative'].includes(m.tone))throw new Error('marker toneが不正です'); applyMarker(root,findSection(root,m.section),m)}
 const markerErrors=validateMarkerPlacement(root); if(markerErrors.length)throw new Error(markerErrors.join('\n')); const normalized=normalizeGutenbergBlocks(serialize(root)); const out=normalized.html; const second=normalizeGutenbergBlocks(out).html; if(out!==second)throw new Error('装飾出力が冪等ではありません'); await writeFile(path.join(dir,'decoration-manifest.json'),JSON.stringify({version:cfg.version||1,source_file:path.basename(src),source_sha256:sha256(html),config_sha256:sha256(JSON.stringify(cfg)),decorated_sha256:sha256(out)},null,2)+'\n'); await atomicWrite(path.join(dir,'article-decorated.html'),out); console.log(`Decorated ${slug}`)}
const slug=argvValue(process.argv,'slug'); if(!slug){console.error('Usage: npm run decorate -- --slug <slug>');process.exit(1)} decorate(slug).catch(e=>{console.error(e.message);process.exit(1)});
