import path from 'node:path';import{readFile,writeFile}from'node:fs/promises';import{argvValue}from'./workflow-utils.mjs';import{atomicWrite,capbox,els,findSection,fragNodes,hasClass,isIn,loadDecorationConfig,parseFragment,replace,sectionNodes,serialize,setAttr,sourceFile,text,assignHeadingIds,attr,before,after,sha256}from'./decoration-utils.mjs';
function unmark(root){for(const n of els(root,'span').filter(n=>hasClass(n,'swl-marker')&&hasClass(n,'mark_yellow')))replace(root,n,n.childNodes||[]);for(const n of els(root,'mark').filter(n=>hasClass(n,'has-swl-deep-01-color')))replace(root,n,n.childNodes||[])}
function wrapList(root,ul,title){setAttr(ul,'class',[attr(ul,'class'),'wp-block-list'].filter(Boolean).join(' '));replace(root,ul,fragNodes(`<!-- wp:loos/cap-block {"className":"is-style-onborder_ttl"} --><div class="swell-block-capbox cap_box is-style-onborder_ttl"><div class="cap_box_ttl"><span>${title}</span></div><div class="cap_box_content"><!-- wp:list -->${serialize({childNodes:[ul]}).trim()}<!-- /wp:list --></div></div><!-- /wp:loos/cap-block -->`))}
function applyMarker(root,heading,m){const nodes=sectionNodes(root,heading); let found=[]; for(const p of nodes.filter(n=>n.tagName==='p'&&!isIn(root,n,x=>['a','ul','ol','table'].includes(x.tagName)||hasClass(x,'swell-block-capbox')))){for(const tn of []); const s=serialize({childNodes:[p]}); if(s.includes(m.text))found.push(p)} if(found.length!==1)throw new Error(`マーカー文字列を一意に特定できません: ${m.text}`); const p=found[0]; const html=serialize({childNodes:[p]}).trim(); const tag=m.tone==='negative'?`<mark style="background-color:rgba(0, 0, 0, 0)" class="has-inline-color has-swl-deep-01-color">${m.text}</mark>`:`<span class="swl-marker mark_yellow">${m.text}</span>`; replace(root,p,fragNodes(html.replace(m.text,tag)));}
export async function decorate(slug){const dir=path.join('articles',slug); const cfg=await loadDecorationConfig(dir); const src=await sourceFile(dir); const html=await readFile(src,'utf8'); const root=parseFragment(html); assignHeadingIds(root); unmark(root); const h2s=els(root,'h2'); if(!h2s.length)throw new Error('H2がありません'); before(root,h2s[0],capbox(cfg.outline?.title||'【この記事でわかること】',h2s.map(h=>({id:attr(h,'id'),title:text(h).trim()})))); for(const h2 of h2s){const nodes=sectionNodes(root,h2), h3s=nodes.filter(n=>n.tagName==='h3'); const ov=(cfg.section_navigation?.overrides||[]).find(o=>o.section&&text(h2).trim()===o.section.heading); const min=ov?.minimum_h3||cfg.section_navigation?.minimum_h3||3; const enabled=ov?.enabled!==false&&cfg.section_navigation?.enabled!==false; if(enabled&&h3s.length>=min){const p=nodes.find(n=>n.tagName==='p'); if(!p)throw new Error(`H2直下の導入文がありません: ${text(h2).trim()}`); after(root,p,capbox(ov?.title||cfg.section_navigation?.default_title||'この章でわかること',h3s.map(h=>({id:attr(h,'id'),title:text(h).trim()}))));}}
 for(const lb of cfg.list_boxes||[]){if(!lb.title||['ここにタイトル','タイトルA','タイトルB','リスト','ポイント','項目'].includes(lb.title))throw new Error('capboxタイトルが不正です'); const h=findSection(root,lb.section); const lists=sectionNodes(root,h).filter(n=>n.tagName==='ul'&&!isIn(root,n,x=>['ul','table','nav','pre','code'].includes(x.tagName)||hasClass(x,'swell-block-capbox')||/cta/i.test(attr(x,'class')))); const ul=lists[(lb.list_index||1)-1]; if(!ul)throw new Error(`対象ulがありません: ${lb.title}`); wrapList(root,ul,lb.title)}
 for(const m of cfg.markers||[]){if(!['positive','negative'].includes(m.tone))throw new Error('marker toneが不正です'); applyMarker(root,findSection(root,m.section),m)}
 const out=serialize(root); const second=serialize(parseFragment(out)); if(out!==second)throw new Error('装飾出力が冪等ではありません'); await writeFile(path.join(dir,'decoration-manifest.json'),JSON.stringify({version:cfg.version||1,source_file:path.basename(src),source_sha256:sha256(html),config_sha256:sha256(JSON.stringify(cfg)),decorated_sha256:sha256(out)},null,2)+'\n'); await atomicWrite(path.join(dir,'article-decorated.html'),out); console.log(`Decorated ${slug}`)}
const slug=argvValue(process.argv,'slug'); if(!slug){console.error('Usage: npm run decorate -- --slug <slug>');process.exit(1)} decorate(slug).catch(e=>{console.error(e.message);process.exit(1)});
