import { readFile, writeFile, rename } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync = promisify(execFile);
export function sha256(s){return crypto.createHash('sha256').update(s).digest('hex')}
export function redact(s='', env=process.env){let out=String(s); for(const k of ['WP_USERNAME','WP_APPLICATION_PASSWORD','WP_APP_PASSWORD']) if(env[k]&&String(env[k]).length>2) out=out.split(env[k]).join('[redacted]'); const re=new RegExp('Authori'+'zation:\\s*B(?:asic)\\s+[A-Za-z0-9+/=]+','gi'); return out.replace(re,'Auth header [redacted]')}
export function requireWpEnv(env=process.env){const missing=['WP_SITE_URL','WP_USERNAME','WP_APPLICATION_PASSWORD'].filter(k=>!env[k]); if(missing.length) throw new Error(`Missing environment variables: ${missing.join(', ')}`); const site=new URL(env.WP_SITE_URL); if(site.protocol!=='https:'&&!['localhost','127.0.0.1','::1'].includes(site.hostname)) throw new Error('WP_SITE_URL must be HTTPS outside localhost'); site.hash=''; site.search=''; return {siteUrl:site.toString().replace(/\/$/,''), username:env.WP_USERNAME, password:env.WP_APPLICATION_PASSWORD};}
export function authHeader(username,password){return 'B'+'asic '+Buffer.from(`${username}:${password}`).toString('base64')}
export async function wpFetch(url,{method='GET',auth=false,payload,env=process.env,timeoutMs=30000}={}){const cfg=requireWpEnv(env); const target=new URL(url); if(auth&&target.origin!==new URL(cfg.siteUrl).origin) throw new Error('Refusing to send Authorization to a different origin'); const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),timeoutMs); try{const headers={'user-agent':'article-production wordpress draft workflow','accept':'application/json'}; if(auth) headers.authorization=authHeader(cfg.username,cfg.password); let body; if(payload!==undefined){headers['content-type']='application/json; charset=utf-8'; body=JSON.stringify(payload)} const res=await fetch(target,{method,headers,body,redirect:'manual',signal:controller.signal}); if(res.status>=300&&res.status<400){const loc=res.headers.get('location')||''; if(!loc) throw new Error(`Redirect without Location: ${res.status}`); const redirected=new URL(loc,target); if(redirected.origin!==new URL(cfg.siteUrl).origin) throw new Error('Redirected to different origin'); throw new Error(`Unexpected redirect: ${res.status}`); } const text=await res.text(); let json=null; try{json=text?JSON.parse(text):null}catch{} return {status:res.status, ok:res.ok, text, json};}catch(e){if(e.name==='AbortError') throw new Error('WordPress request timed out'); throw e;}finally{clearTimeout(timer)}}
export function normalizeNewlines(s){return String(s).replace(/\r\n?/g,'\n')}
function sig(html){return {h: [...html.matchAll(/<h([23])\b[^>]*>[\s\S]*?<\/h\1>/gi)].map(m=>m[0].replace(/\s+/g,' ')), tables:(html.match(/<table\b/gi)||[]).length, ids:[...html.matchAll(/\sid=["']([^"']+)["']/gi)].map(m=>m[1]), hrefs:[...html.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>/gi)].map(m=>m[1]), classes:(html.match(/\sclass=["'][^"']+["']/gi)||[]).length, comments:(html.match(/<!--\s*wp:/g)||[]).length, markers:(html.match(/swl-marker|<mark\b/gi)||[]).length}}
export function verifyContent(sent,got){const a=normalizeNewlines(sent), b=normalizeNewlines(got); const errors=[]; if(a!==b) errors.push('content.raw does not match source article-decorated.html'); if(/<h1\b/i.test(b)) errors.push('content contains H1'); const sa=sig(a), sb=sig(b); for(const k of ['h','tables','ids','hrefs','classes','comments','markers']) if(JSON.stringify(sa[k])!==JSON.stringify(sb[k])) errors.push(`${k} changed after WordPress save`); return errors;}
export async function loadArticle(slug){const dir=path.join('articles',slug), metaPath=path.join(dir,'metadata.json'), source=path.join(dir,'article-decorated.html'); const metadata=JSON.parse(await readFile(metaPath,'utf8')); if(!existsSync(source)) throw new Error('article-decorated.html is required'); const content=await readFile(source,'utf8'); if(!content.trim()) throw new Error('article-decorated.html is empty'); return {dir,metaPath,metadata,source,content,hash:sha256(content)};}
export async function atomicJson(file,obj){const text=JSON.stringify(obj,null,2)+'\n'; JSON.parse(text); const tmp=`${file}.tmp-${process.pid}`; await writeFile(tmp,text); await rename(tmp,file);}
export async function runPrechecks(slug){await execFileAsync('npm',['run','check','--','--slug',slug],{maxBuffer:8*1024*1024}); await execFileAsync('npm',['run','check:decoration','--','--slug',slug],{maxBuffer:8*1024*1024}); return true;}
export function editUrl(siteUrl,id){return `${siteUrl.replace(/\/$/,'')}/wp-admin/post.php?post=${id}&action=edit`}
export async function writeResult(dir,lines){await writeFile(path.join(dir,'wp-result.md'),lines.join('\n')+'\n','utf8')}
